version: "3"
services:
  freenet:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: freenet:docker
    ports:
      - target: 50509
        published: 50599
        protocol: tcp
        mode: host
    volumes:
      - /tmp/freenet-docker:/root/.local/share/freenet
